INSERT INTO TOWNS (name) values('A')
INSERT INTO TOWNS (name) values('B')
INSERT INTO TOWNS (name) values('C')
INSERT INTO TOWNS (name) values('D')
INSERT INTO TOWNS (name) values('E')

INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 5 ,'B' ,'A')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 4 ,'C' ,'B')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 8 ,'D' ,'C')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 8 ,'C' ,'D')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 6 ,'E' ,'D')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 5 ,'D' ,'A')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 2 ,'E' ,'C')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 3 ,'B' ,'E')
INSERT INTO RAILROADS (id, distance, destination_name, origin_name) values (SEQ_RAILROAD.NEXTVAL, 7 ,'E' ,'A')